version: '3.7'
services:
  kong-database:
    image: postgres:9.6
    container_name: kong-database
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    depends_on:
      - kong-database
    image: kong:latest
    container_name: kong-migrations
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    command: kong migrations bootstrap -v

  kong:
    depends_on:
      - kong-database
    image: kong
    container_name: kong
    restart: always
    environment:
      - TZ=Asia/Bangkok
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_NGINX_HTTP_RESOLVER=8.8.8.8
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_PROXY_ACCESS_LOG=/dev/null
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_TRUSTED_IPS=0.0.0.0/0,::/0
      - KONG_REAL_IP_RECURSIVE=on
      - KONG_PLUGINS=bundled, http-method-termination
      - KONG_LUA_PACKAGE_PATH=/etc/kong/plugins/http-method-termination/?.lua;;
    ports:
      - 80:8000
      - 8001:8001
      - 443:8443
    volumes:
      - ./http-method-termination:/etc/kong/plugins/http-method-termination

  konga:
    image: pantsel/konga
    container_name: konga
    restart: always
    ports:
      - 1337:1337
